import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Background from "@/components/background";
import MarginWidthWrapper from "@/components/margin-width-wrapper";
import SideNav from "@/components/side-nav";
import VeiwWindow from "@/components/view-window";
import Header from "@/components/header";
import HeaderMobile from "@/components/header-mobile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Side Nav w/ Sub Menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Background>
          <div className="flex">
            <main className="flex-1">
              <div className="grid grid-cols-12">
                <div className="col-start-2 col-span-2  w-full">
                  <SideNav />
                </div>
                <div className="col-span-6  w-full">
                  <VeiwWindow />
                </div>
                <HeaderMobile />
              </div>
            </main>
          </div>
        </Background>
      </body>
    </html>
  );
}
