import '../styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/header';
import HeaderMobile from '@/components/header-mobile';
import MarginWidthWrapper from '@/components/margin-width-wrapper';
import PageWrapper from '@/components/page-wrapper';
import SideNav from '@/components/side-nav';
import VeiwWindow from '@/components/view-window';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {

  title: 'Side Nav w/ Sub Menu',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-transparent' ${inter.className}`} style={{
        backgroundImage: `url('/images/background.jpg')`,
        backgroundSize: "cover",
        backgroundRepeat: 'no-repeat',
        backgroundPosition: 'center center',
        backgroundAttachment: 'fixed',
        filter: 'brightness(70%)', // Add tint by adjusting brightness
      }}>
        <div className="flex" >
          <SideNav />
          <main className="flex-1">
            <MarginWidthWrapper>
              {/* <Header /> */}
              <HeaderMobile />
              {/* <PageWrapper>{children}</PageWrapper> */}
              <VeiwWindow/>
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}